# Generated by Django 2.0.5 on 2018-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('status', models.IntegerField(choices=[(1, '在售'), (2, '缺货'), (3, '下架')], verbose_name='商品状态')),
            ],
        ),
    ]
