# Generated by Django 2.0.5 on 2018-05-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
    ]
