# Generated by Django 2.0.5 on 2018-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commodity_ptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='img',
            field=models.ImageField(default='', upload_to='src', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
