# Generated by Django 2.0.5 on 2018-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commodity_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='discount',
            field=models.FloatField(default=1, verbose_name='商品折扣'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='img',
            field=models.ImageField(upload_to='./imgs/', verbose_name='商品图片'),
        ),
    ]
