# Generated by Django 2.0.5 on 2018-05-21 10:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180521_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
