# Generated by Django 2.0.5 on 2018-05-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180529_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
    ]
